typedef Country = ({String name, String code});

/// Converts a 2-letter ISO country code to a flag emoji.
/// Falls back to the input string if it's not exactly 2 letters
/// (handles legacy free-text entries gracefully).
String countryCodeToFlag(String code) {
  if (code.length != 2) return code;
  final base = 0x1F1E6 - 65; // 'A' = 65
  final upper = code.toUpperCase();
  return String.fromCharCodes(upper.codeUnits.map((c) => c + base));
}

const List<Country> kCountries = [
  (name: 'Afghanistan', code: 'AF'),
  (name: 'Argentina', code: 'AR'),
  (name: 'Australia', code: 'AU'),
  (name: 'Austria', code: 'AT'),
  (name: 'Belgium', code: 'BE'),
  (name: 'Bolivia', code: 'BO'),
  (name: 'Brazil', code: 'BR'),
  (name: 'Canada', code: 'CA'),
  (name: 'Chile', code: 'CL'),
  (name: 'China', code: 'CN'),
  (name: 'Colombia', code: 'CO'),
  (name: 'Croatia', code: 'HR'),
  (name: 'Czech Republic', code: 'CZ'),
  (name: 'Denmark', code: 'DK'),
  (name: 'Ecuador', code: 'EC'),
  (name: 'Egypt', code: 'EG'),
  (name: 'Estonia', code: 'EE'),
  (name: 'Ethiopia', code: 'ET'),
  (name: 'Finland', code: 'FI'),
  (name: 'France', code: 'FR'),
  (name: 'Germany', code: 'DE'),
  (name: 'Greece', code: 'GR'),
  (name: 'Hungary', code: 'HU'),
  (name: 'Iceland', code: 'IS'),
  (name: 'India', code: 'IN'),
  (name: 'Indonesia', code: 'ID'),
  (name: 'Iran', code: 'IR'),
  (name: 'Iraq', code: 'IQ'),
  (name: 'Ireland', code: 'IE'),
  (name: 'Israel', code: 'IL'),
  (name: 'Italy', code: 'IT'),
  (name: 'Japan', code: 'JP'),
  (name: 'Jordan', code: 'JO'),
  (name: 'Kenya', code: 'KE'),
  (name: 'Latvia', code: 'LV'),
  (name: 'Lithuania', code: 'LT'),
  (name: 'Luxembourg', code: 'LU'),
  (name: 'Malaysia', code: 'MY'),
  (name: 'Mexico', code: 'MX'),
  (name: 'Morocco', code: 'MA'),
  (name: 'Netherlands', code: 'NL'),
  (name: 'New Zealand', code: 'NZ'),
  (name: 'Nigeria', code: 'NG'),
  (name: 'North Korea', code: 'KP'),
  (name: 'Norway', code: 'NO'),
  (name: 'Pakistan', code: 'PK'),
  (name: 'Peru', code: 'PE'),
  (name: 'Philippines', code: 'PH'),
  (name: 'Poland', code: 'PL'),
  (name: 'Portugal', code: 'PT'),
  (name: 'Romania', code: 'RO'),
  (name: 'Russia', code: 'RU'),
  (name: 'Saudi Arabia', code: 'SA'),
  (name: 'Serbia', code: 'RS'),
  (name: 'Singapore', code: 'SG'),
  (name: 'Slovakia', code: 'SK'),
  (name: 'Slovenia', code: 'SI'),
  (name: 'South Africa', code: 'ZA'),
  (name: 'South Korea', code: 'KR'),
  (name: 'Spain', code: 'ES'),
  (name: 'Sweden', code: 'SE'),
  (name: 'Switzerland', code: 'CH'),
  (name: 'Taiwan', code: 'TW'),
  (name: 'Thailand', code: 'TH'),
  (name: 'Turkey', code: 'TR'),
  (name: 'Ukraine', code: 'UA'),
  (name: 'United Arab Emirates', code: 'AE'),
  (name: 'United Kingdom', code: 'GB'),
  (name: 'United States', code: 'US'),
  (name: 'Uruguay', code: 'UY'),
  (name: 'Venezuela', code: 'VE'),
  (name: 'Vietnam', code: 'VN'),
];
